<?php

namespace App\Enums;

enum AuditLogAction: string
{
   case LOGIN = 'LOGIN';
    case LOGOUT = 'LOGOUT';

    case USER_CREATE = 'USER_CREATE';
    case USER_UPDATE = 'USER_UPDATE';
    case USER_DELETE = 'USER_DELETE';
    case USER_RESTORE = 'USER_RESTORE';
    case USER_FORCE_DELETE = 'USER_FORCE_DELETE';

    case USER_CLASS_CREATE = 'USER_CLASS_CREATE';
    case USER_CLASS_UPDATE = 'USER_CLASS_UPDATE';
    case USER_CLASS_DELETE = 'USER_CLASS_DELETE';

    case ELECTION_CREATE = 'ELECTION_CREATE';
    case ELECTION_UPDATE = 'ELECTION_UPDATE';
    case ELECTION_DELETE = 'ELECTION_DELETE';
    case ELECTION_RESTORE = 'ELECTION_RESTORE';
    case ELECTION_FORCE_DELETE = 'ELECTION_FORCE_DELETE';

    case CANDIDATE_CREATE = 'CANDIDATE_CREATE';
    case CANDIDATE_UPDATE = 'CANDIDATE_UPDATE';
    case CANDIDATE_DELETE = 'CANDIDATE_DELETE';

    case VOTE = 'VOTE';
    case CONFIG_CHANGED       = 'CONFIG_CHANGED';
}
